// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ProxyOrigDst struct {
	_    structs.HostLayout
	Ip   uint32
	Port uint16
	_    [2]byte
}

type ProxyTupleKey struct {
	_    structs.HostLayout
	Ip   uint32
	Port uint16
	_    [2]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	ProxyMapOrigdstByCookie = "origdst_by_cookie"
	ProxyMapOrigdstByTuple  = "origdst_by_tuple"
	ProxyProgCgroupConnect4 = "cgroup_connect4"
)

// LoadProxy returns the embedded CollectionSpec for Proxy.
func LoadProxy() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProxyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Proxy: %w", err)
	}

	return spec, err
}

// LoadProxyObjects loads Proxy and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ProxyObjects
//	*ProxyPrograms
//	*ProxyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadProxyObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadProxy()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ProxySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProxySpecs struct {
	ProxyProgramSpecs
	ProxyMapSpecs
	ProxyVariableSpecs
}

// ProxyProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProxyProgramSpecs struct {
	CgroupConnect4 *ebpf.ProgramSpec `ebpf:"cgroup_connect4"`
}

// ProxyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProxyMapSpecs struct {
	OrigdstByCookie *ebpf.MapSpec `ebpf:"origdst_by_cookie"`
	OrigdstByTuple  *ebpf.MapSpec `ebpf:"origdst_by_tuple"`
}

// ProxyVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProxyVariableSpecs struct {
}

// ProxyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadProxyObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProxyObjects struct {
	ProxyPrograms
	ProxyMaps
	ProxyVariables
}

func (o *ProxyObjects) Close() error {
	return _ProxyClose(
		&o.ProxyPrograms,
		&o.ProxyMaps,
	)
}

// ProxyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadProxyObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProxyMaps struct {
	OrigdstByCookie *ebpf.Map `ebpf:"origdst_by_cookie"`
	OrigdstByTuple  *ebpf.Map `ebpf:"origdst_by_tuple"`
}

func (m *ProxyMaps) Close() error {
	return _ProxyClose(
		m.OrigdstByCookie,
		m.OrigdstByTuple,
	)
}

// ProxyVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadProxyObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProxyVariables struct {
}

// ProxyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadProxyObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProxyPrograms struct {
	CgroupConnect4 *ebpf.Program `ebpf:"cgroup_connect4"`
}

func (p *ProxyPrograms) Close() error {
	return _ProxyClose(
		p.CgroupConnect4,
	)
}

func _ProxyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed proxy_bpfeb.o
var _ProxyBytes []byte
