// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TlsKeylogSecretEvent struct {
	_            structs.HostLayout
	Version      uint16
	Label        uint16
	ClientRandom [32]uint8
	Secret       [64]uint8
	SecretLen    uint16
}

type TlsKeylogTlsConfig struct {
	_               structs.HostLayout
	TargetPid       uint32
	ClientRandomOff uint32
	SecretCount     uint32
	SecretOff       [8]uint32
	SecretLen       [8]uint32
	SecretLabel     [8]uint16
	TlsVersion      uint16
	_               [2]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	TlsKeylogMapSecretsRb         = "secrets_rb"
	TlsKeylogMapTlsKeylogConfig   = "tls_keylog_config"
	TlsKeylogProgUprobeTlsKeylog  = "uprobe_tls_keylog"
	TlsKeylogVarUnusedSecretEvent = "unused_secret_event"
)

// LoadTlsKeylog returns the embedded CollectionSpec for TlsKeylog.
func LoadTlsKeylog() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TlsKeylogBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TlsKeylog: %w", err)
	}

	return spec, err
}

// LoadTlsKeylogObjects loads TlsKeylog and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TlsKeylogObjects
//	*TlsKeylogPrograms
//	*TlsKeylogMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTlsKeylogObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTlsKeylog()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TlsKeylogSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TlsKeylogSpecs struct {
	TlsKeylogProgramSpecs
	TlsKeylogMapSpecs
	TlsKeylogVariableSpecs
}

// TlsKeylogProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TlsKeylogProgramSpecs struct {
	UprobeTlsKeylog *ebpf.ProgramSpec `ebpf:"uprobe_tls_keylog"`
}

// TlsKeylogMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TlsKeylogMapSpecs struct {
	SecretsRb       *ebpf.MapSpec `ebpf:"secrets_rb"`
	TlsKeylogConfig *ebpf.MapSpec `ebpf:"tls_keylog_config"`
}

// TlsKeylogVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TlsKeylogVariableSpecs struct {
	UnusedSecretEvent *ebpf.VariableSpec `ebpf:"unused_secret_event"`
}

// TlsKeylogObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTlsKeylogObjects or ebpf.CollectionSpec.LoadAndAssign.
type TlsKeylogObjects struct {
	TlsKeylogPrograms
	TlsKeylogMaps
	TlsKeylogVariables
}

func (o *TlsKeylogObjects) Close() error {
	return _TlsKeylogClose(
		&o.TlsKeylogPrograms,
		&o.TlsKeylogMaps,
	)
}

// TlsKeylogMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTlsKeylogObjects or ebpf.CollectionSpec.LoadAndAssign.
type TlsKeylogMaps struct {
	SecretsRb       *ebpf.Map `ebpf:"secrets_rb"`
	TlsKeylogConfig *ebpf.Map `ebpf:"tls_keylog_config"`
}

func (m *TlsKeylogMaps) Close() error {
	return _TlsKeylogClose(
		m.SecretsRb,
		m.TlsKeylogConfig,
	)
}

// TlsKeylogVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTlsKeylogObjects or ebpf.CollectionSpec.LoadAndAssign.
type TlsKeylogVariables struct {
	UnusedSecretEvent *ebpf.Variable `ebpf:"unused_secret_event"`
}

// TlsKeylogPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTlsKeylogObjects or ebpf.CollectionSpec.LoadAndAssign.
type TlsKeylogPrograms struct {
	UprobeTlsKeylog *ebpf.Program `ebpf:"uprobe_tls_keylog"`
}

func (p *TlsKeylogPrograms) Close() error {
	return _TlsKeylogClose(
		p.UprobeTlsKeylog,
	)
}

func _TlsKeylogClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tlskeylog_bpfel.o
var _TlsKeylogBytes []byte
